# Generated by Django 4.2 on 2023-09-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="gallery_tag",
            field=models.CharField(
                choices=[
                    ("campus", "Campus"),
                    ("transportation", "Transportation"),
                    ("infra", "Infrastructure"),
                    ("lab", "Lab"),
                    ("activity", "Activity"),
                    ("event", "Events"),
                ],
                default="campus",
                max_length=50,
            ),
        ),
    ]
