# Generated by Django 4.2 on 2023-09-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissionenquiry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionenquiry",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
